title: Geeky stories
email: gurdiga@gmail.com
author: Vlad GURDIGA
description:
baseurl: "" # the subpath of your site, e.g. /blog
date_format: "%b %-d, %Y"
permalink: /blog/:year/:month/:day/:title/
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:

# Build settings
markdown: kramdown
theme: jekyll-theme-mint
blog_theme: auto
plugins:
  - jekyll-feed

exclude:
  - CNAME
  - Makefile
  - README.md
  - .viminfo

jekyll_compose:
  auto_open: true
